import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "@/components/layout/ClientLayout.component";
import HeaderLayout from "@/components/layout/HeaderLayout.component";

export const metadata: Metadata = {
  title: "wqls",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col">
        <header className="bg-white shadow py-4 px-48">
          <HeaderLayout />
        </header>

        <main className="mx-48 py-10">
          <ClientLayout>{children}</ClientLayout>
        </main>

        <footer className="text-center text-sm text-gray-500 mt-12 pb-4">
          © 2025 Pejuang OSN. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
