import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "@/components/layout/ClientLayout.component";
import HeaderLayout from "@/components/layout/HeaderLayout.component";
import { AuthProvider } from "@/context/AuthContext.context";

export const metadata: Metadata = {
  title: "wqls",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col">
        <AuthProvider>
          <header className="py-4 px-40 bg-[#EEEEEE]">
            <HeaderLayout />
          </header>

          <main className="">
            <ClientLayout>{children}</ClientLayout>
          </main>

          <footer className="text-center text-sm text-gray-500 mt-96 pb-4">
            © 2025 Pejuang OSN. All rights reserved.
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
