import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "wqls",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900">
        <header className="bg-white shadow p-4">
          <div className="max-w-4xl mx-auto">
            <h1 className="text-xl font-bold text-blue-600">Pejuang OSN</h1>
          </div>
        </header>

        <main className="max-w-4xl mx-auto p-4">{children}</main>

        <footer className="text-center text-sm text-gray-500 mt-12 pb-4">
          © 2025 Pejuang OSN. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
